export {default as Navbar} from './Navbar'
export {default as HomePage} from './Homepage'
export {default as News} from './News'
export {default as Cryptodetails} from './Cryptodetails'
export {default as Cryptocurrencies} from './Cryptocurrencies'
export {default as Exchanges} from './Exchanges'
